### ISSUE TITLE
IMSC 1.1 Editorial task list

### ISSUE THREAD

**Issue by palemieux** [w3c/imsc#294]
- [ ] Change "Extensions" section heading to "Extension Vocabulary"
- [ ] Pick color for deprecation warnings
- [ ] All Image Profile and Text Profile terms should be links
